### ISSUE TITLE
Electronics/software review 

### ISSUE THREAD

**Issue by rebeccamcohen** [rebeccamcohen/DesignSkillsProject#9]
See Release called Milestone03 (v0.1.0)

**Comment by mlp6** [comment]
I think that the topology for your caps before/after the regulator are off.. they should be between power and GND, not in series in the power line.  This allows them to stabilize the voltage, like a LPF.  Also not sure what component the button is attached to (?).

Software -- general scheme looks fine -- ready to get a start on writing the actual code!

**Comment by rebeccamcohen** [comment]
Thanks for the feedback. I have added a new version of my circuit and tried to address these issues (see below or latest commit on r/electronics branch). 

The element that you were unsure about is supposed to be a diode voltage clipper. Did I use it correctly in v0.1.1? 

Additionally, am I using the bypass capacitors correctly in v0.1.1? Should there be another one before the 5V input into the Arduino? 

[circuit_schematic_v0.1.1.pdf](https://github.com/rebeccamcohen/DesignSkillsProject/files/2554782/circuit_schematic_v0.1.1.pdf)

I

**Comment by mlp6** [comment]
Much better!  Only cap you probably don't need is the one in parallel with the diode going into `Din`; that voltage will need to transiently change with the button push, so you don't want to slow it down (potentially), unless you are using that for some form of hardware debouncing of the button press.
